// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 17 14:50:04 2008
// $Id$

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/tglbtn.h>
// end wxGlade

#ifndef WSTATS_H
#define WSTATS_H

// begin wxGlade: ::extracode
// end wxGlade

class WPassStats : public wxDialog
{
public:
    // begin wxGlade: WPassStats::ids
    enum {
        myID_REVEAL = wxID_HIGHEST + 1000,
        myID_QUERYNOW = wxID_HIGHEST + 1002
    };
    // end wxGlade

    WPassStats(struct PassEntry& passentry, wxWindow* parent, int id=wxID_ANY, const wxString& title=wxEmptyString, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    /// Reference to currently displayed password entry.
    struct PassEntry&	passentry;

    /// Update dialog fields from PassEntry structure
    void	UpdateValues();

    /// Create Score Visualization Bitmap
    wxBitmap	MakeScoreBitmap();

private:
    // begin wxGlade: WPassStats::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WPassStats::attributes
    wxStaticBox* sizer5_staticbox;
    wxStaticBox* sizer2_staticbox;
    wxTextCtrl* textctrlDescription;
    wxTextCtrl* textctrlPassword;
    wxToggleButton* buttonReveal;
    wxButton* buttonQueryNow;
    wxStaticText* labelCTime;
    wxStaticText* labelLastQueried;
    wxStaticText* labelNextQuery;
    wxStaticText* labelTimeSpent;
    wxStaticText* labelCorrect;
    wxStaticText* labelIncorrect;
    wxStaticText* labelRevealed;
    wxStaticBitmap* bitmapScores;
    wxStaticText* labelScores;
    wxButton* buttonOK;
    wxButton* buttonCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnButtonReveal(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonQueryNow(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class

#endif // WSTATS_H
