// -*- C++ -*- generated by wxGlade 0.6.2 on Sun Feb 17 09:28:37 2008
// $Id$

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
// end wxGlade

#ifndef PTWMAIN_H
#define PTWMAIN_H

// begin wxGlade: ::extracode
// end wxGlade

class PTWMain : public wxFrame
{
public:
    // begin wxGlade: PTWMain::ids
    enum {
        myID_PASSLIST = wxID_HIGHEST + 1000,
        myID_NEWPASS = wxID_HIGHEST + 1002,
        myID_ABOUT = wxID_HIGHEST + 1004,
        myID_HIDE = wxID_HIGHEST + 1006
    };
    // end wxGlade

    PTWMain(wxWindow* parent, int id=wxID_ANY, const wxString& title=wxEmptyString, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: PTWMain::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PTWMain::attributes
    wxStaticBox* sizer2_staticbox;
    wxListCtrl* listctrlPasslist;
    wxButton* buttonNewPass;
    wxButton* buttonAbout;
    wxButton* buttonHide;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnPasslistItemActivated(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnPasslistItemRightClick(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonNewPass(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonAbout(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonClose(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class

#endif // PTWMAIN_H
