// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Mar  2 17:56:31 2008
// $Id$

#include <wx/wx.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

#ifndef WFILEPROP_H
#define WFILEPROP_H

// begin wxGlade: ::extracode
// end wxGlade

class WFileProperties : public wxDialog
{
public:
    // begin wxGlade: WFileProperties::ids
    // end wxGlade

    WFileProperties(class WCryptoTE* parent, int subfileid, int id=wxID_ANY, const wxString& title=wxEmptyString, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

protected:

    /// Reference to main window
    class WCryptoTE* wmain;

    /// Subfile Index
    int		subfileid;

private:
    // begin wxGlade: WFileProperties::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WFileProperties::attributes
    wxTextCtrl* textIdentifier;
    wxTextCtrl* textFilename;
    wxTextCtrl* textAuthor;
    wxTextCtrl* textSize;
    wxTextCtrl* textCompressed;
    wxTextCtrl* textCTime;
    wxTextCtrl* textMTime;
    wxChoice* choiceType;
    wxChoice* choiceCompression;
    wxChoice* choiceEncryption;
    wxTextCtrl* textSubject;
    wxTextCtrl* textDescription;
    wxStaticLine* staticline1;
    wxButton* buttonOK;
    wxButton* buttonCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnButtonOK(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class

#endif // WFILEPROP_H
