// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Feb 20 10:42:51 2008
// $Id$

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

#ifndef WFINDREPLACE_H
#define WFINDREPLACE_H

// begin wxGlade: ::extracode
// end wxGlade

class WFindReplace : public wxPanel
{
public:
    // begin wxGlade: WFindReplace::ids
    enum {
        myID_COMBO_FIND = wxID_HIGHEST + 1000,
        myID_REPLACEALL = wxID_HIGHEST + 1002
    };
    // end wxGlade

    WFindReplace(class WCryptoTE* parent, int id=wxID_ANY, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

    /// Change dialog to show replacement controls
    void	ShowReplace(bool show);

protected:
    /// Reference to main window
    class WCryptoTE* wmain;

    /// Whether this is a find&replace box
    bool	showreplace;

    /// True if the current search string was found and can be replaced.
    bool	havefound;

private:
    // begin wxGlade: WFindReplace::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WFindReplace::attributes
    wxStaticBox* sizer3_staticbox;
    wxComboBox* comboFind;
    wxStaticText* labelReplace;
    wxComboBox* comboReplace;
    wxCheckBox* checkboxMatchWholeWord;
    wxCheckBox* checkboxMatchCaseInsensitive;
    wxCheckBox* checkboxMatchRegex;
    wxCheckBox* checkboxSearchBackwards;
    wxStaticLine* staticline1;
    wxButton* buttonFind;
    wxButton* buttonReplace;
    wxButton* buttonReplaceAll;
    wxButton* buttonClose;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnComboTextSearch(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonFind(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonReplace(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonReplaceAll(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonClose(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class

#endif // WFINDREPLACE_H
