// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Mar 14 21:10:55 2008
// $Id$

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/listctrl.h>
#include <wx/notebook.h>
// end wxGlade

#ifndef WOPTIONS_H
#define WOPTIONS_H

// begin wxGlade: ::extracode
// end wxGlade

class WOptions : public wxDialog
{
public:
    // begin wxGlade: WOptions::ids
    enum {
        myID_CHECK_BACKUPS = wxID_HIGHEST + 1000,
        myID_CHECK_AUTOCLOSE = wxID_HIGHEST + 1002
    };
    // end wxGlade

    WOptions(wxWindow* parent, int id=wxID_ANY, const wxString& title=wxEmptyString, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: WOptions::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WOptions::attributes
    wxStaticBox* sizerB2_staticbox;
    wxStaticBox* sizerA6_staticbox;
    wxStaticBox* sizerA4_staticbox;
    wxStaticBox* sizerA2_staticbox;
    wxCheckBox* checkboxBackups;
    wxStaticText* labelBackup1;
    wxSpinCtrl* spinctrlBackupNum;
    wxStaticText* labelBackup2;
    wxChoice* choiceBackupLocation;
    wxCheckBox* checkboxAutoClose;
    wxStaticText* labelAutoClose1;
    wxSpinCtrl* spinctrlAutoCloseTime;
    wxStaticText* labelAutoClose2;
    wxCheckBox* checkboxShareLock;
    wxPanel* notebook_pane1;
    wxListCtrl* listctrlTheme;
    wxPanel* notebook_pane2;
    wxNotebook* notebook;
    wxButton* buttonOK;
    wxButton* buttonCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnCheckboxBackups(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCheckboxAutoClose(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnButtonOK(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class

#endif // WOPTIONS_H
